library(Rcpp)
sourceCpp('cppFunctions.cpp')

timesTwo(c(15, 30))

sampleC(c(.5, .5))

mat <- matrix(c(.5, .5, .2, .8), byrow=T, nrow=2)
dimnames(mat) <- list(c("sol", "lluvia"), c("sol", "lluvia"))
mat


mc_transition(1, mat)

traj <- mc_trajectory(init_state = 1, nob=100, trans_mat= mat)
dict <- c("1"="sol","2"="lluvia")
dict[traj]


# TAREA 1: FUNCION INVERSA
#TAREA2: INTEGRAL CON MC CON INTERVALOS DE CONFIANZA
#INSTRUCCIONES TAREA 3:
#HACER UN SHINY QUE RECIBA UN CSV QUE CONTENGA UNA MATRIZ DE TRANSICION
#Y SIMULE UN NUMERO ELEGIDO POR EL USUARIO DE SIMULACIONES DE LA CADENA
#DADO UN ESTADO INICIAL ELEGIDO POR EL USUARIO
#TIENEN QUE USAR LAS FUNCIONES QUE DEFINIMOS HOY EN CLASE
#EN SU PRIMER TIENE QUE CORRER RCPP: SOURCECPP

#HAY 2 PAPPERS QUE HAY QUE LEER, MCMC HISTORY Y EL OTRO DE MARKOV CHAIN MONTE CARLO REVOLUTION, HACER UN REPORTE DE LO QUE LEIMOS, MEDIA O HOJA COMPLETA